---
title: "Diversity"
output: html_document
---

```{r setup, include=FALSE}
library(pacman)
p_load(tidyverse,stringr)



files <- list.files("results/rawdata/")
files <- files[10:18]
files <- paste("results/rawdata/", files,sep="")
files2 <- list.files("results2/rawdata/")
files2 <- files2[10:18]
files2 <- paste("results2/rawdata/", files2,sep="")
files
files <- c(files,files2)

df<- read.csv(files[1])
newCars <- read.csv("Car_aitotal.csv")
newCars$filename <- newCars$AllAiScores
newCars$AllAiScores <- 0
total <- as.data.frame(matrix(0,ncol=4,nrow=1))
colnames(total) <- c(colnames(df), "filename")
for(file in files){
  df<- read.csv(file)
  df$filename <- file
  total <- rbind(total,df)
}

total <- total[-1,]
total <- rbind(total, newCars)


total$kaiscore <- str_remove(total$filename, "results2")
total$kaiscore <- str_remove((str_extract(total$kaiscore, "[:digit:].*")), ".csv")
total$kaiscore<- ifelse(substr(total$kaiscore, 1,1)=="2", str_sub(total$kaiscore, 2),total$kaiscore)

total$AllScores <- as.numeric(total$AllScores)
total$AiRanges <- as.factor(total$AllAiScores)
total$kaiscore <- as.factor(total$kaiscore)

#function for calculating mean kai pr. team
mean_KAI <- function(aiScore, aiRange, nAgents){
  minScore = max(c(40, aiScore-aiRange/2.0))
  maxScore = min(c(150, aiScore+aiRange/2.0))
  aiScores = seq(minScore,maxScore,length.out =  nAgents)
  m <- mean(aiScores)
  return(m)
}

total$aiRange <- as.numeric(as.character(total$AllAiScores))
total$kaiscore_numeric <- as.numeric(as.character(total$kaiscore))
total <- total %>% 
  group_by(kaiscore,AllAiScores) %>% 
  mutate(mean_score = mean(AllScores),
         sd_score = sd(AllScores),
         max_score = max(AllScores),
         mean_kaiscore = mean_KAI(kaiscore_numeric,aiRange,33 ) )

write.csv(total, "all_the_data.csv")
```


```{r}

for(level in levels(total$kaiscore)){
  a <- ggplot(total[total$kaiscore == level,], aes(AllAiScores, AllScores, group = AllAiScores)) +
    geom_point()+   
    stat_summary(fun.y = mean, colour="blue", geom="line", aes(group=1))+
    geom_point(total[total$kaiscore == level,],mapping= aes(AllAiScores,mean_score, color = "red"))+
    geom_errorbar(aes(ymin=mean_score-sd_score, ymax=mean_score+sd_score), width=.2,
                 position=position_dodge(0.05),color="red", alpha = .5)+
    ggtitle(paste("mean Kaiscore = ", as.character(level), sep = " "))+
    xlab("KaiRange")+ylab("Car Design Performance")
  
  print(a)
}
```

```{r}
p_load(brms,rethinking, bayesplot)

total$kaiscore <- as.numeric(as.character(total$kaiscore))
total$scaled_scores <- scale(total$AllScores)
total$kaiscore_scale <- scale(total$kaiscore)
total$aiRange_scale <- scale(total$aiRange)
total$mean_kaiscore_scale <- scale(total$mean_kaiscore)

model <- bf(
  scaled_scores | trunc(ub = 1.5) ~ 1 + mean_kaiscore_scale+aiRange_scale+mean_kaiscore_scale:aiRange_scale, family = gaussian
)

max(total$scaled_scores)
dens(total$scaled_scores)
get_prior(model, data = total)

dens(total$kaiscore)
priors <- c(
  prior(normal(0, .5), class =Intercept),
  prior(normal(0,.1), class = b),
  prior(normal(0,.05), class = sigma)
)


pp <- brm(
  model, 
  prior = priors,
  data = total,
  cores = 4,
  sample_prior = "only",
  control = list(adapt_delta = 0.9)
)


pp_check(pp, nsamples = 100)

mcmc_trace(pp)

ppp <- brm(
  model, 
  prior = priors,
  data = total,
  cores = 4,
  sample_prior = T,
  control = list(adapt_delta = 0.9)
)

pp_check(ppp, nsamples = 100)
mcmc_trace(ppp)

summary(ppp)

hypothesis(ppp, c("aiRange_scale > 0",
                  "mean_kaiscore_scale > 0",
                  "mean_kaiscore_scale:aiRange_scale < 0"))

conditional_effects(ppp)

```

